services:
  - type: web
    name: fastapi-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free

  - type: web
    name: react-frontend
    env: static
    rootDir: .                       # frontend is at repo root
    buildCommand: npm install && npm run build
    staticPublishPath: dist         # dist will be created at root
    plan: free
